### ISSUE TITLE
[Modal] Inspect error with responsive size

### ISSUE THREAD

**Issue by luciob** [melfore/mosaic#330]
When setting `responsive` and the screen size goes too small the StoryBook app crashes.
It happens on both Modal and ModalWithTabs components.

**Comment by luciob** [comment]
This error is generated by StoryBook only in build mode:

```
chunk-UBOPZ7EI.js:398 Uncaught TypeError: Cannot read properties of undefined (reading 'reduce')
    at chunk-UBOPZ7EI.js:398:31215
    at memoizerific (chunk-3J6GS6FI.js:1:3530)
    at reduce.orphansFirst (chunk-UBOPZ7EI.js:398:44168)
    at Array.reduce (<anonymous>)
    at chunk-UBOPZ7EI.js:398:44112
    at mountMemo (chunk-NBCGHFLK.js:69:12247)
    at Object.useMemo (chunk-NBCGHFLK.js:69:19183)
    at useMemo (chunk-QMHPSTMR.js:9:1378)
    at chunk-UBOPZ7EI.js:398:44081
    at renderWithHooks (chunk-NBCGHFLK.js:69:936)
```
